name: Run test node

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.10.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Testing
        run: pnpm test
